### ISSUE TITLE
Resiliency to comments and multiple functions to add by cells :)

### ISSUE THREAD

**Issue by tcosmo** [alexhagen/jdc#1]
Hi, thank you for your plugin which is really nice for educational articles.
Two things that would be great:

- At the moment it's not possible to use %%add_to class when you have comments at the beginning of the cell, for instance:
```python
%%add_to SOM
# Training procedure for a SOM
# data: a N*d matrix, N the number of examples, 
#       d the same as dim_feat=self.shape[2]`
def train(self,data):
     ....
```

But for educational purpose, we are really likely to use this kind of "doc-like" comments.

- Also it would be really nice if the %%add_to command would have effect on all the functions of a cell. As It is useful when we group related functions together in cells, like a sub routine we also want to add in the class. For example:

```python
%%add_to SOM
# Training procedure for a SOM
# data: a N*d matrix, N the number of examples, 
#       d the same as dim_feat=self.shape[2]`
def train(self,data):
     self.initialize_som()
    ....

# Initialize feature vectors of the som
def initialize_som():
     ...
```

Thank you!!!

**Comment by alexhagen** [comment]
Hello,

I'm glad you're liking it.  As for your first question, I propose a slightly different API.  If instead you define your comments like so:

```python
%%add_to SOM
def train(self, data):
    # Training procedure for a SOM
    # data: a N*d matrix, N the number of examples, 
    #       d the same as dim_feat=self.shape[2]`
    ...
```

then `jdc` should work as is.  Additionally, if you were to define the function like this:

```python
%%add_to SOM
def train(self, data):
    """ Training procedure for a SOM
         data: a N*d matrix, N the number of examples, 
                  d the same as dim_feat=self.shape[2]`"""
    ...
```

then `jdc` should work as is, and you could access that comment using `SOM.train.__doc__` later, if needed.

Does this work?  If not, I'll add an ability to define the comments the way you suggested.

For the second comment, I'll try to look into it over the weekend.  Cheers!

**Comment by tcosmo** [comment]
Yes it works really well!
It's nice I didn't know about this `__doc__` feature in python :o 
Thank you again!

**Comment by alexhagen** [comment]
I'm glad that works for you!

I've committed to make it possible to define multiple methods in one cell - so if you pull the repo and reload your notebooks it should have the new feature.  I have a working multi-method cell in the readme, as an example.  I haven't done it in a very robust way, and I plan to make it more robust in the future; let me know if you have any problems in the meantime.

I hope this helps!
