### ISSUE TITLE
UsageError: Cell magic `%%add_to` not found.

### ISSUE THREAD

**Issue by richcmwang** [alexhagen/jdc#4]
Hi,
jdc sudden stopped work today with message:

UsageError: Cell magic `%%add_to` not found.

I am using Python 3.7.4.  Any suggestion how to fix this?  Thanks.

**Comment by sajjadhossanshimanto** [comment]
You need to import `jdc` first 
Run a cell with `import jdc` before yor use.

**Comment by sumsumcity** [comment]
I think this issue can be closed.
